import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

export function parseFrontmatter(md) {
  const m = md.match(/^---\n([\s\S]*?)\n---/);
  const fm = {};
  if (!m) return fm;
  for (const line of m[1].split("\n")) {
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    fm[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
  }
  return fm;
}

export function buildChangesIndex(changesDir) {
  const files = readdirSync(changesDir).filter((f) => f.endsWith(".md") && !f.startsWith("_"));
  const rows = files.map((f) => {
    const fm = parseFrontmatter(readFileSync(join(changesDir, f), "utf8"));
    return {
      name: f.replace(/\.md$/, ""),
      pr: Number(fm.pr) || 0,
      date: fm.date ?? "",
      type: fm.type ?? "",
      roadmap: fm.roadmap && fm.roadmap !== "null" ? fm.roadmap : "—",
    };
  });
  rows.sort((a, b) => b.date.localeCompare(a.date) || b.pr - a.pr);
  const body = rows
    .map((r) => `| ${r.date} | #${r.pr} | \`${r.type}\` | ${r.roadmap} | [[changes/${r.name}]] |`)
    .join("\n");
  return `# Changes — Index

> Reverse-chronological log of every merged PR. Auto-generated by \`tools/brain-sync\` — do not edit by hand.

| Date | PR | Type | Roadmap | Note |
|------|----|------|---------|------|
${body}
`;
}
