import { stripPrefix } from "./classify.mjs";

export function noteBasename(pr, cls) {
  const date = (pr.mergedAt ?? "0000-00-00").slice(0, 10);
  return `${date}-PR-${pr.number}-${cls.slug}.md`;
}

function firstParagraph(body) {
  const cleaned = (body ?? "").replace(/\r\n/g, "\n").trim();
  if (!cleaned) return "_No description provided._";
  return cleaned.split(/\n\s*\n/)[0].trim();
}

export function renderChangeNote(pr, cls) {
  const date = (pr.mergedAt ?? "").slice(0, 10) || "unknown";
  const title = stripPrefix(pr.title) || pr.title || "(untitled)";

  const frontmatter = [
    "---",
    `pr: ${pr.number}`,
    `date: ${date}`,
    `author: ${pr.author}`,
    `type: ${cls.type}`,
    `plugins: [${cls.plugins.join(", ")}]`,
    `roadmap: ${cls.roadmap ?? "null"}`,
    `files_changed: ${pr.files.length}`,
    "---",
  ].join("\n");

  const changedAreas = cls.plugins.length
    ? cls.plugins.map((p) => `- [[components/${p}]]`).join("\n")
    : "- _Repo-level change (no plugin under `plugins/` touched)._";

  const planning = cls.roadmap
    ? `- Advances roadmap item **${cls.roadmap}** → [[planning/roadmap]]`
    : "- _No roadmap item tagged._";

  return `${frontmatter}

# PR #${pr.number} — ${title}

> \`${cls.type}\`${cls.roadmap ? ` · Roadmap ${cls.roadmap}` : ""} · merged ${date} · by @${pr.author}

## Summary

${firstParagraph(pr.body)}

## Changed areas

${changedAreas}

## Decisions & rationale

- _Enrich: record or link the decision behind this change, e.g. \`decisions/ADR-XXXX\`._

## Planning

${planning}

---
_Auto-generated by \`tools/brain-sync\`. Frontmatter is machine-owned; prose below "Summary" is safe to enrich._
`;
}
